<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Lenovoi5" failures="1" tests="1" name="BankingApp Test(failed)" time="7.086" errors="0" timestamp="2024-07-23T16:55:55 IST">
  <testcase classname="com.inetBank.testCases.TC_loginDDT_02" name="LoginDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.IllegalArgumentException: Row 3 does not exist in sheet Sheet1">
      <![CDATA[java.lang.RuntimeException: java.lang.IllegalArgumentException: Row 3 does not exist in sheet Sheet1
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.IllegalArgumentException: Row 3 does not exist in sheet Sheet1
at com.inetBank.utilities.XLUtils.getData(XLUtils.java:139)
at com.inetBank.testCases.TC_loginDDT_02.loginDataProvider(TC_loginDDT_02.java:94)
... 25 more
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- LoginDDT -->
</testsuite> <!-- BankingApp Test(failed) -->
